### PR TITLE
Don't require token for GET

### PR DESCRIPTION
**Pull request by kou**
We can request GET without API token.

### CODE REVIEW

**Comment by kou** [comment]
For example:

```console
% curl https://ci.appveyor.com/api/projects/sckott/cowsay
{
  "project": {
    "projectId": 44589,
    "accountId": 13586,
    "accountName": "sckott",
    "builds": [],
...
```

**Comment by sckott** [comment]
okay, but do you get more data fields that are given when a valid token is given, or no?

**Comment by kou** [comment]
I got the same data with/without a valid token.
But I just confirmed this for https://ci.appveyor.com/api/projects/groonga/pgroonga . Other API may have a difference.

**Comment by sckott** [comment]
okay, i'm asking Appveyor about this as they say they want a token with every request, just trying to clarify first

**Comment by sckott** [comment]
@kou given the response at https://github.com/appveyor/website/issues/613 from Appveyor, i lean towards requiring a key to avoid confusion when a user is requesting data from a mix of public and private projects

what do you think?

**Comment by kou** [comment]
In my case, I will use this library only for public projects. So token isn't required. If token is still required, I'll use this library with a dummy (invalid) token such as `dummy-token`. Because AppVeyor API returns a response with invalid token:

```console
$ curl -H "Authorization: Bearer dummy-token" https://ci.appveyor.com/api/projects/groonga/pgroonga
{
  "project": {
    "projectId": 114495,
    "accountId": 15636,
    "accountName": "groonga",
    "builds": [],
...
```
My case may be a minor case. So you can choose what you like.

**Comment by sckott** [comment]
i agree it probably makes most sense to not require it - and makes first time use a nicer  experience as a user may not have an API key yet

**Pull request merged**
